# Generated by Django 4.2 on 2023-04-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('petname', models.CharField(max_length=100)),
                ('petspecies', models.CharField(max_length=100)),
                ('bkdate', models.DateField()),
                ('bktime', models.CharField(max_length=15)),
                ('service', models.CharField(max_length=100)),
                ('charge', models.IntegerField()),
                ('status', models.CharField(default='New Booking', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('ph', models.CharField(max_length=50)),
                ('feed', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=28)),
                ('Username', models.CharField(max_length=28, unique=True)),
                ('Email', models.CharField(max_length=28)),
                ('Phone_Number', models.IntegerField()),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
